# Generated by Django 5.2.14 on 2026-05-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSITUweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
